"use client";

import React, { useMemo, useState } from "react";
import { DndContext, KeyboardSensor, PointerSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { getTypographyClassName } from "../../../config/typography.ts";
import { cn } from "../../../utils/cn.ts";

export type KanbanColumnDef<S extends string> = { id: S; label: string; ariaLabel: string; emptyTitle?: string; emptyDescription?: string };
export type KanbanColumnLoadState = { isLoading?: boolean; error?: string | null; hasMore?: boolean; onLoadMore?: () => void };
export type KanbanConfig<T, S extends string> = { columns: readonly KanbanColumnDef<S>[]; statusAccessor: (item: T) => S; renderCard: (item: T) => React.ReactNode; canDrop: (item: T, target: S) => boolean; onItemMove: (item: T, from: S, target: S) => Promise<void> | void; getColumnLoadState?: (status: S) => KanbanColumnLoadState; isItemPending?: (item: T) => boolean };
export type DataKanbanProps<T, S extends string> = { items: T[]; keyExtractor: (item: T, index: number) => string; kanbanConfig: KanbanConfig<T, S> };

function Lane<S extends string>({ column, children }: { column: KanbanColumnDef<S>; children: React.ReactNode }) { const { setNodeRef } = useDroppable({ id: column.id }); return <section ref={setNodeRef} aria-label={column.ariaLabel} className="w-80 shrink-0 snap-start rounded-[var(--radius-card)] border border-[var(--color-border)] bg-[var(--color-surface-muted)] p-3"><h2 className={cn(getTypographyClassName("label"), "mb-3 text-[var(--color-on-surface)]")}>{column.label}</h2>{children}</section>; }
function Card({ id, disabled, children }: { id: string; disabled: boolean; children: React.ReactNode }) { const { attributes, listeners, setNodeRef, transform } = useDraggable({ id, disabled }); return <div ref={setNodeRef} {...attributes} {...listeners} style={transform ? { transform: `translate3d(${transform.x}px, ${transform.y}px, 0)` } : undefined} className={cn("touch-none", disabled && "opacity-60")}>{children}</div>; }
export function DataKanban<T, S extends string>({ items, keyExtractor, kanbanConfig }: DataKanbanProps<T, S>) {
 const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 8 } }), useSensor(KeyboardSensor)); const [active, setActive] = useState<string | null>(null);
 const grouped = useMemo(() => { const map = new Map<S, T[]>(); kanbanConfig.columns.forEach(c => map.set(c.id, [])); items.forEach(i => map.get(kanbanConfig.statusAccessor(i))?.push(i)); return map; }, [items, kanbanConfig]);
 const byId = useMemo(() => new Map(items.map((i, n) => [keyExtractor(i, n), i])), [items, keyExtractor]);
 const onDragEnd = (e: DragEndEvent) => { setActive(null); const item = e.active.id ? byId.get(String(e.active.id)) : undefined; const target = e.over?.id as S | undefined; if (!item || !target) return; const from = kanbanConfig.statusAccessor(item); if (from !== target && kanbanConfig.canDrop(item, target)) void kanbanConfig.onItemMove(item, from, target); };
 return <DndContext sensors={sensors} onDragStart={e => setActive(String(e.active.id))} onDragCancel={() => setActive(null)} onDragEnd={onDragEnd}><div className="flex gap-4 overflow-x-auto snap-x snap-mandatory pb-2">{kanbanConfig.columns.map(column => { const state = kanbanConfig.getColumnLoadState?.(column.id) ?? {}; const lane = grouped.get(column.id) ?? []; return <Lane key={column.id} column={column}><div className="flex flex-col gap-3">{state.isLoading ? [1,2,3].map(n => <div key={n} className="h-32 animate-pulse rounded-[var(--radius-card)] bg-[var(--color-surface)]" />) : lane.map((item, index) => { const id = keyExtractor(item, index); return <Card key={id} id={id} disabled={active === id || Boolean(kanbanConfig.isItemPending?.(item))}>{kanbanConfig.renderCard(item)}</Card>; })}{!state.isLoading && !lane.length ? <p className={cn(getTypographyClassName("bodySm"), "rounded-[var(--radius-card)] border border-dashed border-[var(--color-border)] p-4 text-[var(--color-muted)]")}>{column.emptyDescription ?? "No requests in this stage."}</p> : null}{state.error ? <p className={cn(getTypographyClassName("bodySm"), "text-[var(--color-muted)]")}>{state.error}</p> : null}{state.hasMore && state.onLoadMore ? <button type="button" onClick={state.onLoadMore} className={cn(getTypographyClassName("buttonSecondary"), "rounded-[var(--radius-button)] border border-[var(--color-border)] px-3 py-2 text-[var(--color-on-surface)]")}>Load more</button> : null}</div></Lane>; })}</div></DndContext>;
}
