import type { LanguageCode } from './contracts';

const I18N_LABELS = {
  en: {
    beginJourney: 'BEGIN THE JOURNEY',
    brochureTheme: 'BROCHURE THEME',
    routeMapOverview: 'Route map overview',
    hotelTelephonePrefix: 'TEL',
    consideredInFull: 'Considered in Full',
    classic: 'Classic',
    image: 'Image',
    routeMapTitle: 'Your Journey, Mapped',
    routeMapLead:
      'Follow a curated path through Vietnam, from timeless landmarks to refined luxury stopovers. Select a destination on the map or list to explore the highlights along the way.',
    daySingular: 'DAY',
    dayPlural: 'DAYS',
    highlights: 'Highlights',
    overnight: 'Overnight',
    meals: 'Meals',
    privateServices: 'Private Services',
    stayPlanning: 'Stay Planning',
    inclusionsTitle: 'Inclusions',
    exclusionsTitle: 'Exclusions',
    importantNote: 'Important Note',
    perTraveler: 'per traveler',
    total: 'group total',
    explore: 'Explore',
    chatWhatsapp: 'CHAT ON WHATSAPP',
    sendEmail: 'SEND AN EMAIL',
    tryAgain: 'Try Again',
    returnHome: 'Return Home',
    duration: 'Duration',
    route: 'Route',
    routeMapNav: 'Route Map',
    itineraryNav: 'Itinerary',
    quotationNav: 'Quotation',
    termsNav: 'Terms',
    journeyOverviewKicker: 'JOURNEY OVERVIEW',
    journeyOverviewTitle: 'A Journey Shaped Around You',
    routeMapDescription: 'Follow the route and explore the considered moments along the way.',
    routeMapUnavailable: 'Route coordinates will be available after the itinerary facts are updated.',
    itineraryTitle: 'Your Journey, Day by Day',
    itineraryDescription: 'A considered rhythm of places, stays and experiences.',
    staysDividerTitle: 'Selected Stays',
    staysDividerTagline: 'Places chosen for rest, character and a sense of place.',
    staysDividerClosing: 'Every stay is selected around the rhythm of your journey.',
    journeyTogetherKicker: 'THE JOURNEY, BROUGHT TOGETHER',
    journeyTogetherTitle: 'Considered in Full',
    journeyTogetherTagline:
      'The stays, private arrangements and experiences described so far are gathered here as one considered whole. What follows is the practical outline of the journey—quietly arranged, carefully paced and shaped around your comfort throughout.',
    journeyTogetherClosing: 'The next section presents the journey in practical terms.',
    pricingTitle: 'Journey Investment',
    pricingDescription: 'A clear view of the investment for this considered journey.',
    inclusionsSectionTitle: 'What Is Included',
    inclusionsDescription: 'Detailed inclusions and exclusions for this proposal.',
    bookingTermsTitle: 'Booking Terms',
    bookingTermsDescription: 'Terms are shared clearly before confirmation.',
    termDepositLabel: 'Deposit',
    termDepositBody:
      'A deposit of 30% of the total tour cost is required upon confirmation of the booking. This deposit is non-refundable.\n\nFor bookings confirmed within 60 days of arrival, full payment of 100% of the total tour cost is required at the time of confirmation.',
    termBalanceLabel: 'Balance',
    termBalanceBody:
      'The remaining 70% balance must be paid no later than 60 days prior to the scheduled arrival date.',
    termCancellationLabel: 'Cancellation',
    termCancellationBody:
      'Written notice required. Cancellation fees apply based on arrival date:\n• > 45 days prior: Deposit forfeited (30%)\n• 45 – 31 days prior: 50% of total tour cost\n• 30 – 20 days prior: 75% of total tour cost\n• < 20 days prior: 100% of total tour cost\n\nAny non-refundable payments, cancellation charges or penalties imposed by hotels, airlines, cruise operators and other service providers may also apply.',
    footerText: 'This confidential quotation has been prepared exclusively for your journey.',
    pdfWhitespaceSlogan: 'Your journeys through Vietnam and Indochina, shaped around living heritage, quiet landscapes and the luxury of time.',
    brochureSections: 'Brochure sections',
    previousImage: 'Previous image',
    nextImage: 'Next image',
    itineraryImages: 'Itinerary images',
    showImage: 'Show image {index}',
    loading: 'Loading quotation',
    loadingBody: 'Preparing your brochure.',
    errorTitle: 'Unable to load quotation',
    errorBody: 'Please try again in a moment.',
    notFoundTitle: 'Quotation not found',
    notFoundBody: 'This quotation may no longer be available.',
  },
  vi: {
    beginJourney: 'BẮT ĐẦU HÀNH TRÌNH',
    brochureTheme: 'BROCHURE THEME',
    routeMapOverview: 'Tổng quan bản đồ hành trình',
    hotelTelephonePrefix: 'ĐT',
    consideredInFull: 'Được Cân Nhắc Trọn Vẹn',
    classic: 'Bản đồ',
    image: 'Hình ảnh',
    routeMapTitle: 'Hành Trình Được Vẽ Thành Bản Đồ',
    routeMapLead:
      'Theo dấu một hành trình được tuyển chọn qua Việt Nam, từ những địa danh vượt thời gian đến các điểm dừng nghỉ sang trọng. Hãy chọn một điểm trên bản đồ hoặc trong danh sách để khám phá các điểm nhấn dọc đường.',
    daySingular: 'NGÀY',
    dayPlural: 'NGÀY',
    highlights: 'Điểm nhấn',
    overnight: 'Lưu trú',
    meals: 'Bữa ăn',
    privateServices: 'Dịch vụ riêng',
    stayPlanning: 'Lưu trú chọn lọc',
    inclusionsTitle: 'Bao gồm',
    exclusionsTitle: 'Không bao gồm',
    importantNote: 'Lưu ý quan trọng',
    perTraveler: 'mỗi khách',
    total: 'tổng đoàn',
    explore: 'Khám phá',
    chatWhatsapp: 'NHẮN WHATSAPP',
    sendEmail: 'GỬI EMAIL',
    tryAgain: 'Thử lại',
    returnHome: 'Về trang chủ',
    duration: 'Thời lượng',
    route: 'Hành trình',
    routeMapNav: 'Bản đồ hành trình',
    itineraryNav: 'Lịch trình',
    quotationNav: 'Báo giá',
    termsNav: 'Điều khoản',
    journeyOverviewKicker: 'TỔNG QUAN HÀNH TRÌNH',
    journeyOverviewTitle: 'Hành Trình Được Thiết Kế Riêng',
    routeMapDescription: 'Theo dõi lộ trình và khám phá những điểm nhấn được cân nhắc kỹ lưỡng.',
    routeMapUnavailable: 'Tọa độ hành trình sẽ có sau khi dữ liệu lịch trình được cập nhật.',
    itineraryTitle: 'Hành Trình Theo Từng Ngày',
    itineraryDescription: 'Nhịp điệu hài hòa giữa điểm đến, lưu trú và trải nghiệm.',
    staysDividerTitle: 'Lưu Trú Chọn Lọc',
    staysDividerTagline: 'Những chốn nghỉ được chọn vì sự thư thái, bản sắc và cảm nhận địa phương.',
    staysDividerClosing: 'Mỗi nơi lưu trú được chọn theo nhịp điệu hành trình của bạn.',
    journeyTogetherKicker: 'HÀNH TRÌNH ĐƯỢC GẮN KẾT TRỌN VẸN',
    journeyTogetherTitle: 'Được Cân Nhắc Trọn Vẹn',
    journeyTogetherTagline:
      'Các điểm lưu trú, dịch vụ riêng tư và trải nghiệm được mô tả đến đây tạo nên một tổng thể gắn kết. Phần tiếp theo trình bày lịch trình thực tế và chi phí của chuyến đi.',
    journeyTogetherClosing: 'Phần tiếp theo trình bày các điều khoản thực tế của chuyến đi.',
    pricingTitle: 'Đầu Tư Cho Hành Trình',
    pricingDescription: 'Tổng quan rõ ràng về chi phí cho hành trình được thiết kế riêng.',
    inclusionsSectionTitle: 'Dịch Vụ Bao Gồm',
    inclusionsDescription: 'Chi tiết các dịch vụ bao gồm và không bao gồm trong đề xuất này.',
    bookingTermsTitle: 'Điều Khoản Đặt Chỗ',
    bookingTermsDescription: 'Điều khoản được chia sẻ minh bạch trước khi xác nhận.',
    termDepositLabel: 'Đặt cọc',
    termDepositBody:
      'Khoản đặt cọc 30% tổng chi phí chuyến đi được yêu cầu ngay khi xác nhận đặt chỗ. Khoản đặt cọc này không hoàn lại.\n\nĐối với các đặt chỗ được xác nhận trong vòng 60 ngày trước ngày khởi hành, cần thanh toán 100% tổng chi phí tại thời điểm xác nhận.',
    termBalanceLabel: 'Thanh toán còn lại',
    termBalanceBody:
      'Số tiền 70% còn lại phải được thanh toán không muộn hơn 60 ngày trước ngày khởi hành dự kiến.',
    termCancellationLabel: 'Hủy dịch vụ',
    termCancellationBody:
      'Yêu cầu thông báo bằng văn bản. Phí hủy dịch vụ áp dụng dựa trên ngày khởi hành:\n• > 45 ngày trước khởi hành: Mất cọc (30%)\n• 45 – 31 ngày trước khởi hành: 50% tổng chi phí tour\n• 30 – 20 ngày trước khởi hành: 75% tổng chi phí tour\n• < 20 ngày trước khởi hành: 100% tổng chi phí tour\n\nMọi khoản thanh toán không hoàn lại hoặc chi phí phạt từ khách sạn, hãng hàng không, du thuyền và đối tác cung cấp dịch vụ có thể áp dụng thêm.',
    footerText: 'Báo giá bảo mật này được chuẩn bị riêng cho hành trình của bạn.',
    pdfWhitespaceSlogan: 'Những hành trình qua Việt Nam và Đông Dương được định hình bởi di sản sống, cảnh quan tĩnh lặng và sự xa xỉ của thời gian.',
    brochureSections: 'Các phần của brochure',
    previousImage: 'Ảnh trước',
    nextImage: 'Ảnh tiếp theo',
    itineraryImages: 'Ảnh hành trình',
    showImage: 'Hiển thị ảnh {index}',
    loading: 'Đang tải báo giá',
    loadingBody: 'Đang chuẩn bị brochure của bạn.',
    errorTitle: 'Không thể tải báo giá',
    errorBody: 'Vui lòng thử lại sau ít phút.',
    notFoundTitle: 'Không tìm thấy báo giá',
    notFoundBody: 'Báo giá này có thể không còn khả dụng.',
  },
  ar: {
    beginJourney: 'ابدأ الرحلة',
    brochureTheme: 'نمط الكتيب',
    routeMapOverview: 'نظرة عامة على خريطة الرحلة',
    hotelTelephonePrefix: 'هاتف',
    consideredInFull: 'اختيار مدروس بالكامل',
    classic: 'الخريطة',
    image: 'الصور',
    routeMapTitle: 'رحلتك مرسومة على الخريطة',
    routeMapLead:
      'اتبع مسارا منسقا عبر فيتنام، من المعالم الخالدة إلى محطات التوقف الفاخرة. اختر وجهة من الخريطة أو من القائمة لاستكشاف أبرز اللحظات على الطريق.',
    daySingular: 'اليوم',
    dayPlural: 'الأيام',
    highlights: 'أبرز المحطات',
    overnight: 'الإقامة',
    meals: 'الوجبات',
    privateServices: 'الخدمات الخاصة',
    stayPlanning: 'تنسيق الإقامة',
    inclusionsTitle: 'يشمل',
    exclusionsTitle: 'لا يشمل',
    importantNote: 'ملاحظة مهمة',
    perTraveler: 'لكل مسافر',
    total: 'إجمالي المجموعة',
    explore: 'استكشف',
    chatWhatsapp: 'التواصل عبر واتساب',
    sendEmail: 'إرسال بريد إلكتروني',
    tryAgain: 'حاول مرة أخرى',
    returnHome: 'العودة للرئيسية',
    duration: 'المدة',
    route: 'المسار',
    routeMapNav: 'خريطة الرحلة',
    itineraryNav: 'برنامج الرحلة',
    quotationNav: 'عرض السعر',
    termsNav: 'الشروط',
    journeyOverviewKicker: 'نظرة عامة على الرحلة',
    journeyOverviewTitle: 'رحلة صممت من أجلك',
    routeMapDescription: 'اتبع المسار واكتشف اللحظات المختارة بعناية على الطريق.',
    routeMapUnavailable: 'ستتوفر إحداثيات المسار بعد تحديث بيانات برنامج الرحلة.',
    itineraryTitle: 'رحلتك يوما بيوم',
    itineraryDescription: 'إيقاع مدروس من الأماكن والإقامات والتجارب.',
    staysDividerTitle: 'إقامات مختارة',
    staysDividerTagline: 'أماكن اختيرت للراحة والشخصية والإحساس بالمكان.',
    staysDividerClosing: 'كل إقامة مختارة لتناسب إيقاع رحلتك.',
    journeyTogetherKicker: 'الرحلة متكاملة معاً',
    journeyTogetherTitle: 'اختيار مدروس بالكامل',
    journeyTogetherTagline:
      'الإقامات والترتيبات الخاصة والتجارب الموضحة حتى الآن مجمعة هنا ككل مدروس.',
    journeyTogetherClosing: 'يقدم القسم التالي الرحلة بشروط عملية.',
    pricingTitle: 'استثمار الرحلة',
    pricingDescription: 'عرض واضح لاستثمار هذه الرحلة المصممة بعناية.',
    inclusionsSectionTitle: 'ما يشمله البرنامج',
    inclusionsDescription: 'تفاصيل الخدمات المشمولة والمستثناة من هذا المقترح.',
    bookingTermsTitle: 'شروط الحجز',
    bookingTermsDescription: 'تتم مشاركة الشروط بوضوح قبل التأكيد.',
    termDepositLabel: 'العربون',
    termDepositBody:
      'يلزم دفع عربون بنسبة 30% من إجمالي تكلفة الجولة عند تأكيد الحجز. هذا العربون غير قابل للاسترداد.\n\nبالنسبة للحجوزات المؤكدة في غضون 60 يومًا من تاريخ الوصول، يلزم سداد كامل المبلغ بنسبة 100% في وقت التأكيد.',
    termBalanceLabel: 'الرصيد المتبقي',
    termBalanceBody:
      'يجب سداد الرصيد المتبقي البالغ 70% في موعد لا يتجاوز 60 يومًا قبل تاريخ الوصول المقرر.',
    termCancellationLabel: 'الإلغاء',
    termCancellationBody:
      'يلزم تقديم إشعار خطي. تطبق رسوم الإلغاء بناءً على تاريخ الوصول:\n• أكثر من 45 يومًا: مصادرة العربون (30%)\n• 45 - 31 يومًا: 50% من إجمالي تكلفة الجولة\n• 30 - 20 يومًا: 75% من إجمالي تكلفة الجولة\n• أقل من 20 يومًا: 100% من إجمالي تكلفة الجولة\n\nقد تنطبق أيضًا أي مدفوعات غير قابلة للاسترداد أو غرامات مفروضة من الفنادق وشركات الطيران ومقدمي الخدمات.',
    footerText: 'أعد عرض السعر السري هذا حصريا لرحلتك.',
    pdfWhitespaceSlogan: 'رحلاتكم عبر فيتنام والهند الصينية تصوغها التقاليد الحية والمناظر الهادئة وفخامة الوقت.',
    brochureSections: 'أقسام الكتيب',
    previousImage: 'الصورة السابقة',
    nextImage: 'الصورة التالية',
    itineraryImages: 'صور الرحلة',
    showImage: 'عرض الصورة {index}',
    loading: 'جار تحميل عرض السعر',
    loadingBody: 'يجري تجهيز الكتيب الخاص بك.',
    errorTitle: 'تعذر تحميل عرض السعر',
    errorBody: 'يرجى المحاولة مجددا بعد قليل.',
    notFoundTitle: 'لم يتم العثور على عرض السعر',
    notFoundBody: 'قد لا يكون عرض السعر هذا متاحا الآن.',
  },
} as const;

export function getLanguageLabels(lang: LanguageCode) {
  return I18N_LABELS[lang] ?? I18N_LABELS.en;
}

export const PRICING_AMOUNT_LABELS: Record<
  LanguageCode,
  {
    perTraveler: string;
    perAdult: string;
    perChild: string;
    adultsLabel: string;
    childrenLabel: string;
    total: string;
  }
> = {
  en: {
    perTraveler: 'per traveler',
    perAdult: 'per adult',
    perChild: 'per child',
    adultsLabel: 'Adults',
    childrenLabel: 'Children',
    total: 'group total',
  },
  vi: {
    perTraveler: 'mỗi khách',
    perAdult: 'mỗi người lớn',
    perChild: 'mỗi trẻ em',
    adultsLabel: 'Người lớn',
    childrenLabel: 'Trẻ em',
    total: 'tổng đoàn',
  },
  ar: {
    perTraveler: 'لكل مسافر',
    perAdult: 'لكل بالغ',
    perChild: 'لكل طفل',
    adultsLabel: 'بالغين',
    childrenLabel: 'أطفال',
    total: 'إجمالي المجموعة',
  },
};
