import type { LanguageCode } from './contracts';

const I18N_LABELS = {
  en: {
    beginJourney: 'BEGIN THE JOURNEY',
    brochureTheme: 'BROCHURE THEME',
    routeMapOverview: 'Route map overview',
    hotelTelephonePrefix: 'TEL',
    confirmedMainOption: 'CONFIRMED MAIN OPTION',
    consideredInFull: 'Considered in Full',
    classic: 'Classic',
    image: 'Image',
    routeMapTitle: 'Your Journey, Mapped',
    routeMapLead:
      'Follow a curated path through Vietnam, from timeless landmarks to refined luxury stopovers. Select a destination on the map or list to explore the highlights along the way.',
    daySingular: 'DAY',
    dayPlural: 'DAYS',
    highlights: 'Highlights',
    overnight: 'Overnight',
    meals: 'Meals',
    privateServices: 'Private Services',
    stayPlanning: 'Stay Planning',
    inclusionsTitle: 'Inclusions',
    exclusionsTitle: 'Exclusions',
    importantNote: 'Important Note',
    perTraveler: 'per traveler',
    total: 'group total',
    explore: 'Explore',
    chatWhatsapp: 'CHAT ON WHATSAPP',
    sendEmail: 'SEND AN EMAIL',
    tryAgain: 'Try Again',
    returnHome: 'Return Home',
    duration: 'Duration',
    route: 'Route',
    routeMapNav: 'Route Map',
    itineraryNav: 'Itinerary',
    quotationNav: 'Quotation',
    termsNav: 'Terms',
    journeyOverviewKicker: 'JOURNEY OVERVIEW',
    journeyOverviewTitle: 'A Journey Shaped Around You',
    routeMapDescription: 'Follow the route and explore the considered moments along the way.',
    itineraryTitle: 'Your Journey, Day by Day',
    itineraryDescription: 'A considered rhythm of places, stays and experiences.',
    staysDividerTitle: 'Selected Stays',
    staysDividerTagline: 'Places chosen for rest, character and a sense of place.',
    staysDividerClosing: 'Every stay is selected around the rhythm of your journey.',
    pricingTitle: 'Journey Investment',
    pricingDescription: 'A clear view of the investment for this considered journey.',
    inclusionsSectionTitle: 'What Is Included',
    inclusionsDescription: 'Detailed inclusions and exclusions for this proposal.',
    bookingTermsTitle: 'Booking Terms',
    bookingTermsDescription: 'Terms are shared clearly before confirmation.',
    finalizationKicker: 'NEXT STEPS',
    finalizationTitle: 'Finalization Checklist',
    finalizationDescription: 'The remaining details we will confirm together.',
    footerText: 'This confidential quotation has been prepared exclusively for your journey.',
    pdfWhitespaceSlogan: 'Your journeys through Vietnam and Indochina, shaped around living heritage, quiet landscapes and the luxury of time.',
    brochureSections: 'Brochure sections',
    previousImage: 'Previous image',
    nextImage: 'Next image',
    itineraryImages: 'Itinerary images',
    showImage: 'Show image {index}',
    loading: 'Loading quotation',
    loadingBody: 'Preparing your brochure.',
    errorTitle: 'Unable to load quotation',
    errorBody: 'Please try again in a moment.',
    notFoundTitle: 'Quotation not found',
    notFoundBody: 'This quotation may no longer be available.',
  },
  vi: {
    beginJourney: 'BẮT ĐẦU HÀNH TRÌNH',
    brochureTheme: 'BROCHURE THEME',
    routeMapOverview: 'Tổng quan bản đồ hành trình',
    hotelTelephonePrefix: 'ĐT',
    confirmedMainOption: 'LỰA CHỌN CHÍNH ĐÃ XÁC NHẬN',
    consideredInFull: 'Được Cân Nhắc Trọn Vẹn',
    classic: 'Bản đồ',
    image: 'Hình ảnh',
    routeMapTitle: 'Hành Trình Được Vẽ Thành Bản Đồ',
    routeMapLead:
      'Theo dấu một hành trình được tuyển chọn qua Việt Nam, từ những địa danh vượt thời gian đến các điểm dừng nghỉ sang trọng. Hãy chọn một điểm trên bản đồ hoặc trong danh sách để khám phá các điểm nhấn dọc đường.',
    daySingular: 'NGÀY',
    dayPlural: 'NGÀY',
    highlights: 'Điểm nhấn',
    overnight: 'Lưu trú',
    meals: 'Bữa ăn',
    privateServices: 'Dịch vụ riêng',
    stayPlanning: 'Lưu trú chọn lọc',
    inclusionsTitle: 'Bao gồm',
    exclusionsTitle: 'Không bao gồm',
    importantNote: 'Lưu ý quan trọng',
    perTraveler: 'mỗi khách',
    total: 'tổng đoàn',
    explore: 'Khám phá',
    chatWhatsapp: 'NHẮN WHATSAPP',
    sendEmail: 'GỬI EMAIL',
    tryAgain: 'Thử lại',
    returnHome: 'Về trang chủ',
    duration: 'Thời lượng',
    route: 'Hành trình',
    routeMapNav: 'Bản đồ hành trình',
    itineraryNav: 'Lịch trình',
    quotationNav: 'Báo giá',
    termsNav: 'Điều khoản',
    journeyOverviewKicker: 'TỔNG QUAN HÀNH TRÌNH',
    journeyOverviewTitle: 'Hành Trình Được Thiết Kế Riêng',
    routeMapDescription: 'Theo dõi lộ trình và khám phá những điểm nhấn được cân nhắc kỹ lưỡng.',
    itineraryTitle: 'Hành Trình Theo Từng Ngày',
    itineraryDescription: 'Nhịp điệu hài hòa giữa điểm đến, lưu trú và trải nghiệm.',
    staysDividerTitle: 'Lưu Trú Chọn Lọc',
    staysDividerTagline: 'Những chốn nghỉ được chọn vì sự thư thái, bản sắc và cảm nhận địa phương.',
    staysDividerClosing: 'Mỗi nơi lưu trú được chọn theo nhịp điệu hành trình của bạn.',
    pricingTitle: 'Đầu Tư Cho Hành Trình',
    pricingDescription: 'Tổng quan rõ ràng về chi phí cho hành trình được thiết kế riêng.',
    inclusionsSectionTitle: 'Dịch Vụ Bao Gồm',
    inclusionsDescription: 'Chi tiết các dịch vụ bao gồm và không bao gồm trong đề xuất này.',
    bookingTermsTitle: 'Điều Khoản Đặt Chỗ',
    bookingTermsDescription: 'Điều khoản được chia sẻ minh bạch trước khi xác nhận.',
    finalizationKicker: 'BƯỚC TIẾP THEO',
    finalizationTitle: 'Thông Tin Xác Nhận',
    finalizationDescription: 'Những chi tiết còn lại chúng ta sẽ cùng xác nhận.',
    footerText: 'Báo giá bảo mật này được chuẩn bị riêng cho hành trình của bạn.',
    pdfWhitespaceSlogan: 'Những hành trình qua Việt Nam và Đông Dương được định hình bởi di sản sống, cảnh quan tĩnh lặng và sự xa xỉ của thời gian.',
    brochureSections: 'Các phần của brochure',
    previousImage: 'Ảnh trước',
    nextImage: 'Ảnh tiếp theo',
    itineraryImages: 'Ảnh hành trình',
    showImage: 'Hiển thị ảnh {index}',
    loading: 'Đang tải báo giá',
    loadingBody: 'Đang chuẩn bị brochure của bạn.',
    errorTitle: 'Không thể tải báo giá',
    errorBody: 'Vui lòng thử lại sau ít phút.',
    notFoundTitle: 'Không tìm thấy báo giá',
    notFoundBody: 'Báo giá này có thể không còn khả dụng.',
  },
  ar: {
    beginJourney: 'ابدأ الرحلة',
    brochureTheme: 'نمط الكتيب',
    routeMapOverview: 'نظرة عامة على خريطة الرحلة',
    hotelTelephonePrefix: 'هاتف',
    confirmedMainOption: 'الخيار الرئيسي المؤكد',
    consideredInFull: 'اختيار مدروس بالكامل',
    classic: 'الخريطة',
    image: 'الصور',
    routeMapTitle: 'رحلتك مرسومة على الخريطة',
    routeMapLead:
      'اتبع مسارا منسقا عبر فيتنام، من المعالم الخالدة إلى محطات التوقف الفاخرة. اختر وجهة من الخريطة أو من القائمة لاستكشاف أبرز اللحظات على الطريق.',
    daySingular: 'اليوم',
    dayPlural: 'الأيام',
    highlights: 'أبرز المحطات',
    overnight: 'الإقامة',
    meals: 'الوجبات',
    privateServices: 'الخدمات الخاصة',
    stayPlanning: 'تنسيق الإقامة',
    inclusionsTitle: 'يشمل',
    exclusionsTitle: 'لا يشمل',
    importantNote: 'ملاحظة مهمة',
    perTraveler: 'لكل مسافر',
    total: 'إجمالي المجموعة',
    explore: 'استكشف',
    chatWhatsapp: 'التواصل عبر واتساب',
    sendEmail: 'إرسال بريد إلكتروني',
    tryAgain: 'حاول مرة أخرى',
    returnHome: 'العودة للرئيسية',
    duration: 'المدة',
    route: 'المسار',
    routeMapNav: 'خريطة الرحلة',
    itineraryNav: 'برنامج الرحلة',
    quotationNav: 'عرض السعر',
    termsNav: 'الشروط',
    journeyOverviewKicker: 'نظرة عامة على الرحلة',
    journeyOverviewTitle: 'رحلة صممت من أجلك',
    routeMapDescription: 'اتبع المسار واكتشف اللحظات المختارة بعناية على الطريق.',
    itineraryTitle: 'رحلتك يوما بيوم',
    itineraryDescription: 'إيقاع مدروس من الأماكن والإقامات والتجارب.',
    staysDividerTitle: 'إقامات مختارة',
    staysDividerTagline: 'أماكن اختيرت للراحة والشخصية والإحساس بالمكان.',
    staysDividerClosing: 'كل إقامة مختارة لتناسب إيقاع رحلتك.',
    pricingTitle: 'استثمار الرحلة',
    pricingDescription: 'عرض واضح لاستثمار هذه الرحلة المصممة بعناية.',
    inclusionsSectionTitle: 'ما يشمله البرنامج',
    inclusionsDescription: 'تفاصيل الخدمات المشمولة والمستثناة من هذا المقترح.',
    bookingTermsTitle: 'شروط الحجز',
    bookingTermsDescription: 'تتم مشاركة الشروط بوضوح قبل التأكيد.',
    finalizationKicker: 'الخطوات التالية',
    finalizationTitle: 'قائمة التحقق النهائية',
    finalizationDescription: 'التفاصيل المتبقية التي سنؤكدها معا.',
    footerText: 'أعد عرض السعر السري هذا حصريا لرحلتك.',
    pdfWhitespaceSlogan: 'رحلاتكم عبر فيتنام والهند الصينية تصوغها التقاليد الحية والمناظر الهادئة وفخامة الوقت.',
    brochureSections: 'أقسام الكتيب',
    previousImage: 'الصورة السابقة',
    nextImage: 'الصورة التالية',
    itineraryImages: 'صور الرحلة',
    showImage: 'عرض الصورة {index}',
    loading: 'جار تحميل عرض السعر',
    loadingBody: 'يجري تجهيز الكتيب الخاص بك.',
    errorTitle: 'تعذر تحميل عرض السعر',
    errorBody: 'يرجى المحاولة مجددا بعد قليل.',
    notFoundTitle: 'لم يتم العثور على عرض السعر',
    notFoundBody: 'قد لا يكون عرض السعر هذا متاحا الآن.',
  },
} as const;

export function getLanguageLabels(lang: LanguageCode) {
  return I18N_LABELS[lang] ?? I18N_LABELS.en;
}

export const PRICING_AMOUNT_LABELS: Record<LanguageCode, { perTraveler: string; total: string }> = {
  en: { perTraveler: 'per traveler', total: 'group total' },
  vi: { perTraveler: 'mỗi khách', total: 'tổng đoàn' },
  ar: { perTraveler: 'لكل مسافر', total: 'إجمالي المجموعة' },
};
