import type {
  ColorScopeId,
  SectionDisplayConfig,
  ThemeColorRecipe,
  ThemeDefinition,
  PublicSectionId,
  TypographySlotMap,
} from '../types';

const defaultVisible = {
  desktop: true,
  mobile: true,
  pdf: true,
} as const;

const defaultHidden = {
  desktop: false,
  mobile: false,
  pdf: false,
} as const;

function slots(map: TypographySlotMap): TypographySlotMap {
  return map;
}

const sectionColorScopes: Record<PublicSectionId, ColorScopeId> = {
  nav: 'appChrome',
  hero: 'heroOverlay',
  letter: 'editorialPaper',
  routeMap: 'routeMap',
  itineraryDivider: 'chapterContrast',
  itinerary: 'editorialPaper',
  hotels: 'editorialPaper',
  staysDivider: 'editorialPaper',
  pricing: 'pricing',
  inclusionsExclusions: 'details',
  paymentTerms: 'details',
  designer: 'designer',
  footer: 'footer',
};

const defaultColorSlots: SectionDisplayConfig['colorSlots'] = {
  action: 'primary',
  badge: 'primary',
  link: 'secondary',
  marker: 'timelineMarker',
  timeline: 'timelineRoute',
};

function config(
  section: PublicSectionId,
  overrides: Omit<SectionDisplayConfig, 'colorScope' | 'colorSlots'> &
    Partial<Pick<SectionDisplayConfig, 'colorScope' | 'colorSlots'>>
): SectionDisplayConfig {
  return {
    colorScope: sectionColorScopes[section],
    colorSlots: defaultColorSlots,
    ...overrides,
  };
}

const colorRecipe: ThemeColorRecipe = {
  scopes: {
    page: {
      surface: 'canvas', onSurface: 'ink', muted: 'mutedInk', accent: 'accent', accentAlt: 'accentAlt',
      border: { color: 'accent', opacity: 0.16 }, strongBorder: { color: 'accent', opacity: 0.3 },
      action: {
        primary: { surface: 'contrast', text: 'onContrast', border: { color: 'contrast', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'accent', opacity: 0.32 } },
      },
      timeline: { route: 'accentAlt', marker: 'contrast', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0.14 }, ornamentOpacity: 0.18,
      viewModeAdjustments: { mobile: { border: { color: 'accent', opacity: 0.2 } }, pdf: { shadow: { color: 'ink', opacity: 0 }, ornamentOpacity: 0.12 } },
    },
    appChrome: {
      surface: 'paper', onSurface: 'ink', muted: 'mutedInk', accent: 'accent', accentAlt: 'accentAlt',
      border: { color: 'accent', opacity: 0.18 }, strongBorder: { color: 'accent', opacity: 0.32 },
      action: {
        primary: { surface: 'accent', text: 'ink', border: { color: 'accent', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'accent', opacity: 0.28 } },
      },
      timeline: { route: 'accentAlt', marker: 'contrast', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0.24 }, ornamentOpacity: 0,
      viewModeAdjustments: { mobile: { shadow: { color: 'ink', opacity: 0.3 } }, pdf: { shadow: { color: 'ink', opacity: 0 } } },
    },
    heroOverlay: {
      surface: 'storyContrast', onSurface: 'onContrast', muted: 'onContrast', accent: 'accentAlt', accentAlt: 'accentAlt',
      border: { color: 'onContrast', opacity: 0.24 }, strongBorder: { color: 'onContrast', opacity: 0.4 },
      action: {
        primary: { surface: 'accent', text: 'ink', border: { color: 'accent', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'onContrast', border: { color: 'onContrast', opacity: 0.36 } },
      },
      timeline: { route: 'accentAlt', marker: 'storyContrast', active: 'accentAlt' },
      overlay: { start: { color: 'storyContrast', opacity: 0.35 }, end: { color: 'storyContrast', opacity: 0.20 } },
      shadow: { color: 'ink', opacity: 0.26 }, ornamentOpacity: 0.15,
      viewModeAdjustments: { mobile: { overlay: { start: { color: 'storyContrast', opacity: 0.35 }, end: { color: 'storyContrast', opacity: 0.20 } } }, pdf: { overlay: { start: { color: 'storyContrast', opacity: 0.35 }, end: { color: 'storyContrast', opacity: 0.20 } } } },
    },
    editorialPaper: {
      surface: 'paper', onSurface: 'ink', muted: 'mutedInk', accent: 'accent', accentAlt: 'accentAlt',
      border: { color: 'accent', opacity: 0.16 }, strongBorder: { color: 'accent', opacity: 0.3 },
      action: {
        primary: { surface: 'accent', text: 'onContrast', border: { color: 'accent', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'accent', opacity: 0.32 } },
      },
      timeline: { route: 'accentAlt', marker: 'accent', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0.1 }, ornamentOpacity: 0.18,
      viewModeAdjustments: { pdf: { shadow: { color: 'ink', opacity: 0 } } },
    },
    routeMap: {
      surface: 'paper', onSurface: 'ink', muted: 'mutedInk', accent: 'accent', accentAlt: 'accentAlt',
      border: { color: 'accentAlt', opacity: 0.28 }, strongBorder: { color: 'accentAlt', opacity: 0.42 },
      action: {
        primary: { surface: 'accent', text: 'onContrast', border: { color: 'accent', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'accentAlt', opacity: 0.42 } },
      },
      timeline: { route: 'accentAlt', marker: 'accent', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0.14 }, ornamentOpacity: 0.14,
      viewModeAdjustments: { pdf: { shadow: { color: 'ink', opacity: 0 }, ornamentOpacity: 0.1 } },
    },
    chapterContrast: {
      surface: 'storyContrast', onSurface: 'onContrast', muted: 'onContrast', accent: 'accentAlt', accentAlt: 'accentAlt',
      border: { color: 'onContrast', opacity: 0.2 }, strongBorder: { color: 'onContrast', opacity: 0.38 },
      action: {
        primary: { surface: 'storyContrast', text: 'onContrast', border: { color: 'storyContrast', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'onContrast', border: { color: 'onContrast', opacity: 0.34 } },
      },
      timeline: { route: 'accentAlt', marker: 'storyContrast', active: 'accentAlt' },
      overlay: { start: { color: 'storyContrast', opacity: 0.9 }, end: { color: 'storyContrast', opacity: 0.6 } },
      shadow: { color: 'ink', opacity: 0.26 }, ornamentOpacity: 0.14,
      viewModeAdjustments: { pdf: { shadow: { color: 'ink', opacity: 0 } } },
    },
    pricing: {
      surface: 'investmentSurface', onSurface: 'investmentText', muted: 'investmentText', accent: 'investmentText', accentAlt: 'investmentText',
      border: { color: 'investmentText', opacity: 0.2 }, strongBorder: { color: 'investmentText', opacity: 0.38 },
      action: {
        primary: { surface: 'investmentSurface', text: 'investmentText', border: { color: 'investmentText', opacity: 0.8 } },
        secondary: { surface: 'transparent', text: 'investmentText', border: { color: 'investmentText', opacity: 0.34 } },
      },
      timeline: { route: 'accentAlt', marker: 'investmentText', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0.26 }, ornamentOpacity: 0.14,
      viewModeAdjustments: { pdf: { shadow: { color: 'ink', opacity: 0 } } },
    },
    details: {
      surface: 'canvas', onSurface: 'ink', muted: 'mutedInk', accent: 'accent', accentAlt: 'accentAlt',
      border: { color: 'accent', opacity: 0.16 }, strongBorder: { color: 'accent', opacity: 0.3 },
      action: {
        primary: { surface: 'accent', text: 'onContrast', border: { color: 'accent', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'accent', opacity: 0.32 } },
      },
      timeline: { route: 'accentAlt', marker: 'accent', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0.06 }, ornamentOpacity: 0,
      viewModeAdjustments: { pdf: { shadow: { color: 'ink', opacity: 0 } } },
    },
    brandJourney: {
      surface: 'accent', onSurface: 'ink', muted: 'mutedInk', accent: 'accentAlt', accentAlt: 'accentAlt',
      border: { color: 'ink', opacity: 0.24 }, strongBorder: { color: 'ink', opacity: 0.42 },
      action: {
        primary: { surface: 'accent', text: 'ink', border: { color: 'ink', opacity: 0.8 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'ink', opacity: 0.42 } },
      },
      timeline: { route: 'accentAlt', marker: 'ink', active: 'accentAlt' },
      shadow: { color: 'contrast', opacity: 0.2 }, ornamentOpacity: 0.12,
      viewModeAdjustments: { pdf: { shadow: { color: 'contrast', opacity: 0 } } },
    },
    designer: {
      surface: 'paper', onSurface: 'ink', muted: 'mutedInk', accent: 'accent', accentAlt: 'accentAlt',
      border: { color: 'accent', opacity: 0.16 }, strongBorder: { color: 'accent', opacity: 0.3 },
      action: {
        primary: { surface: 'accent', text: 'onContrast', border: { color: 'accent', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'accent', opacity: 0.32 } },
      },
      timeline: { route: 'accentAlt', marker: 'accent', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0.1 }, ornamentOpacity: 0.16,
      viewModeAdjustments: { pdf: { shadow: { color: 'ink', opacity: 0 } } },
    },
    footer: {
      surface: 'canvas', onSurface: 'ink', muted: 'mutedInk', accent: 'accent', accentAlt: 'accentAlt',
      border: { color: 'accent', opacity: 0.12 }, strongBorder: { color: 'accent', opacity: 0.22 },
      action: {
        primary: { surface: 'accent', text: 'onContrast', border: { color: 'accent', opacity: 1 } },
        secondary: { surface: 'transparent', text: 'ink', border: { color: 'accent', opacity: 0.24 } },
      },
      timeline: { route: 'accentAlt', marker: 'accent', active: 'accentAlt' },
      shadow: { color: 'ink', opacity: 0 }, ornamentOpacity: 0,
    },
  },
};

const typographyMap: ThemeDefinition['typographyMap'] = {
  nav: slots({
    title: 'navTitle',
    metaPrimary: 'navMeta',
    action: 'buttonPrimary',
    label: 'overline',
    link: 'topbarSectionLink',
  }),
  hero: slots({
    kicker: 'chapterKicker',
    title: 'pageTitle',
    body: 'heroLede',
    metaPrimary: 'heroMetaPrimary',
    metaSecondary: 'heroMetaSecondary',
    action: 'buttonPrimary',
    footer: 'navMeta',
  }),
  letter: slots({
    kicker: 'chapterKicker',
    title: 'chapterTitle',
    body: 'letterBody',
    quote: 'letterHighlight',
    signature: 'signatureName',
    metaSecondary: 'signatureMeta',
  }),
  routeMap: slots({
    title: 'chapterTitle',
    body: 'routeMapBody',
    kicker: 'label',
    metaPrimary: 'timelineTitle',
    metaSecondary: 'timelineMeta',
    index: 'timelineMeta',
    badge: 'timelineTitle',
    action: 'buttonSecondary',
  }),
  itineraryDivider: slots({
    kicker: 'chapterKicker',
    title: 'chapterTitle',
    body: 'bodyLg',
    metaPrimary: 'heroMetaPrimary',
    metaSecondary: 'heroMetaSecondary',
    action: 'buttonSecondary',
  }),
  itinerary: slots({
    kicker: 'chapterKicker',
    title: 'chapterTitle',
    body: 'dayBody',
    metaPrimary: 'dayTitle',
    metaSecondary: 'timelineMeta',
    label: 'label',
    action: 'buttonSecondary',
  }),
  hotels: slots({
    title: 'chapterTitle',
    body: 'hotelBody',
    metaPrimary: 'hotelTitle',
    metaSecondary: 'hotelMeta',
    label: 'label',
    action: 'buttonSecondary',
  }),
  staysDivider: slots({
    kicker: 'chapterKicker',
    title: 'chapterTitle',
    body: 'bodyLg',
    footer: 'quote',
    action: 'buttonSecondary',
  }),
  pricing: slots({
    kicker: 'chapterKicker',
    title: 'chapterTitle',
    body: 'investmentMeta',
    price: 'investmentValue',
    metaPrimary: 'investmentTitle',
    metaSecondary: 'investmentMeta',
    label: 'label',
    index: 'caption',
    action: 'buttonSecondary',
    badge: 'timelineTitle',
  }),

  inclusionsExclusions: slots({
    title: 'chapterTitle',
    body: 'bodyMd',
    metaPrimary: 'hotelTitle',
    metaSecondary: 'bodySm',
    action: 'buttonSecondary',
  }),

  paymentTerms: slots({
    kicker: 'chapterKicker',
    title: 'chapterTitle',
    label: 'termLabel',
    body: 'termBody',
    action: 'buttonSecondary',
    metaPrimary: 'label',
  }),
  designer: slots({
    kicker: 'chapterKicker',
    title: 'chapterTitle',
    quote: 'designerQuote',
    body: 'bodyMd',
    signature: 'signatureName',
    metaSecondary: 'signatureMeta',
    action: 'buttonSecondary',
    label: 'label',
    footer: 'caption',
  }),
  footer: slots({
    body: 'footerText',
    metaSecondary: 'caption',
  }),
};

export const brochureTheme: ThemeDefinition = {
  id: 'brochure',
  label: 'Brochure Theme',
  supportedViewModes: ['desktop', 'mobile', 'pdf'],
  pageShell: 'shell-none',
  sectionOrder: [
    'nav',
    'hero',
    'letter',
    'routeMap',
    'itineraryDivider',
    'itinerary',
    'hotels',
    'staysDivider',
    'pricing',
    'inclusionsExclusions',
    'paymentTerms',
    'designer',
    'footer',
  ],
  layoutVariants: [
    'hero-cover',
    'centered-stack',
    'editorial-split-55-45',
    'editorial-split-50-50',
    'timeline-with-sidebar',
    'day-story-grid',
    'hotel-editorial-odd-even',
    'full-bleed-divider',
    'pricing-ledger',
    'two-column-panel',
    'term-rows',
    'profile-split',
    'footer-minimal',
    'nav-overlay-fixed',
    'letter-sidebar-220',
    'route-map-interactive',
    'itinerary-day-single',
    'itinerary-day-multi',
    'stays-editorial-split',
    'pricing-investment-ledger',
    'inclusions-panels',
    'designer-editorial-profile',
  ],
  ornamentRegistry: {
    frame: 'display-ornament display-ornament--frame',
    cloud: 'display-ornament display-ornament--cloud',
    cyclo: 'display-ornament display-ornament--cyclo',
    lantern: 'display-ornament display-ornament--lantern',
    temple: 'display-ornament display-ornament--temple',
    terrace: 'display-ornament display-ornament--terrace',
  },
  assetRegistry: {
    border: '/assets/brands/indochine_icon/border.svg',
    cyclo: '/assets/brands/indochine_icon/xich_lo.svg',
    cloud: '/assets/brands/indochine_icon/cloud.svg',
    lantern: '/assets/brands/indochine_icon/den_long.svg',
    temple: '/assets/brands/indochine_icon/chua_1_cot.svg',
    terrace: '/assets/brands/indochine_icon/ruong_bac_thang.svg',
  },
  sectionBehaviorPresets: {
    nav: {
      scrollMode: 'hero-overlay',
    },
    routeMap: {
      interaction: 'interactive',
    },
    itinerary: {
      alternatingLayouts: true,
    },
  },
  typographyMap,
  colorRecipe,
  pdfRules: {
    fixedPageSize: 'A4',
    pageClassName: 'pdf-page-shell',
    preserveColor: true,
  },
  sectionConfigs: {
    nav: {
      desktop: config('nav', {
        layoutVariant: 'nav-overlay-fixed',
        shellVariant: 'shell-none',
        backgroundVariant: 'transparent',
        spacingVariant: 'tight',
        alignment: 'split',
        stickyBehavior: 'fixed-overlay',
        ornamentVariant: 'frame',
        surfaceStyle: 'glass',
        sectionIntroStyle: 'hero',
        interactionPreset: 'none',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.nav,
        printBehavior: { pageTemplate: 'cover', avoidBreakInside: true },
      }),
      mobile: config('nav', {
        layoutVariant: 'nav-overlay-fixed',
        shellVariant: 'shell-none',
        backgroundVariant: 'transparent',
        spacingVariant: 'tight',
        alignment: 'split',
        stickyBehavior: 'fixed-overlay',
        ornamentVariant: 'frame',
        surfaceStyle: 'glass',
        sectionIntroStyle: 'hero',
        mobileOrderStrategy: 'nav-condensed',
        interactionPreset: 'none',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.nav,
        printBehavior: { pageTemplate: 'cover', avoidBreakInside: true },
      }),
      pdf: config('nav', {
        layoutVariant: 'nav-overlay-fixed',
        shellVariant: 'shell-none',
        backgroundVariant: 'transparent',
        spacingVariant: 'tight',
        alignment: 'split',
        stickyBehavior: 'static',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'hero',
        interactionPreset: 'none',
        visibilityByViewMode: { desktop: true, mobile: true, pdf: false },
        ornaments: [],
        typographySlots: typographyMap.nav,
        printBehavior: { pageTemplate: 'cover', avoidBreakInside: true },
      }),
    },
    hero: {
      desktop: config('hero', {
        layoutVariant: 'hero-cover',
        shellVariant: 'shell-full-bleed',
        backgroundVariant: 'image-overlay',
        spacingVariant: 'immersive',
        alignment: 'start',
        ornamentVariant: 'none',
        surfaceStyle: 'full-bleed',
        sectionIntroStyle: 'hero',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.hero,
        printBehavior: { pageTemplate: 'cover', pageBreakAfter: true, avoidBreakInside: true },
      }),
      mobile: config('hero', {
        layoutVariant: 'hero-cover',
        shellVariant: 'shell-full-bleed',
        backgroundVariant: 'image-overlay',
        spacingVariant: 'immersive',
        alignment: 'start',
        ornamentVariant: 'none',
        surfaceStyle: 'full-bleed',
        sectionIntroStyle: 'hero',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.hero,
        printBehavior: { pageTemplate: 'cover', pageBreakAfter: true, avoidBreakInside: true },
      }),
      pdf: config('hero', {
        layoutVariant: 'hero-cover',
        shellVariant: 'shell-pdf-page',
        backgroundVariant: 'image-overlay',
        spacingVariant: 'page',
        alignment: 'start',
        surfaceStyle: 'full-bleed',
        sectionIntroStyle: 'hero',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.hero,
        printBehavior: { pageTemplate: 'cover', pageBreakAfter: true, avoidBreakInside: true },
      }),
    },
    letter: {
      desktop: config('letter', {
        layoutVariant: 'letter-sidebar-220',
        shellVariant: 'shell-indochine-frame',
        backgroundVariant: 'surfaceWhite',
        spacingVariant: 'airy',
        alignment: 'split',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.letter,
        printBehavior: { pageTemplate: 'editorial', avoidBreakInside: true, pageGroupWithNext: true },
      }),
      mobile: config('letter', {
        layoutVariant: 'letter-sidebar-220',
        shellVariant: 'shell-indochine-soft',
        backgroundVariant: 'surfaceWhite',
        spacingVariant: 'comfortable',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        mobileOrderStrategy: 'letter-stacked',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.letter,
        printBehavior: { pageTemplate: 'editorial', avoidBreakInside: true, pageGroupWithNext: true },
      }),
      pdf: config('letter', {
        layoutVariant: 'letter-sidebar-220',
        shellVariant: 'shell-pdf-page-framed',
        backgroundVariant: 'surfaceWhite',
        spacingVariant: 'page',
        alignment: 'split',
        surfaceStyle: 'framed',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.letter,
        printBehavior: { pageTemplate: 'editorial', avoidBreakInside: true, pageGroupWithNext: true },
      }),
    },
    routeMap: {
      desktop: config('routeMap', {
        layoutVariant: 'route-map-interactive',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'canvas',
        spacingVariant: 'airy',
        alignment: 'split',
        ornamentVariant: 'cloud',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        interactionPreset: 'route-map',
        visibilityByViewMode: defaultVisible,
        ornaments: ['cloud'],
        typographySlots: typographyMap.routeMap,
        printBehavior: { pageTemplate: 'timeline', allowCondensedVariant: true, pageBreakAfter: true },
      }),
      mobile: config('routeMap', {
        layoutVariant: 'route-map-interactive',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'canvas',
        spacingVariant: 'comfortable',
        alignment: 'start',
        ornamentVariant: 'cloud',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        mobileOrderStrategy: 'route-map-stacked',
        interactionPreset: 'route-map',
        visibilityByViewMode: defaultVisible,
        ornaments: ['cloud'],
        typographySlots: typographyMap.routeMap,
        printBehavior: { pageTemplate: 'timeline', allowCondensedVariant: true, pageBreakAfter: true },
      }),
      pdf: config('routeMap', {
        layoutVariant: 'route-map-interactive',
        shellVariant: 'shell-pdf-page',
        backgroundVariant: 'canvas',
        spacingVariant: 'page',
        alignment: 'split',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'editorial',
        interactionPreset: 'none',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.routeMap,
        printBehavior: { pageTemplate: 'timeline', allowCondensedVariant: true, pageBreakAfter: true },
      }),
    },
    itineraryDivider: {
      desktop: config('itineraryDivider', {
        layoutVariant: 'full-bleed-divider',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'image-overlay',
        spacingVariant: 'immersive',
        alignment: 'start',
        ornamentVariant: 'lantern',
        surfaceStyle: 'full-bleed',
        sectionIntroStyle: 'chapter',
        visibilityByViewMode: defaultHidden,
        ornaments: ['lantern'],
        typographySlots: typographyMap.itineraryDivider,
        printBehavior: { pageTemplate: 'chapter', pageBreakBefore: true, pageBreakAfter: true, avoidBreakInside: true },
      }),
      mobile: config('itineraryDivider', {
        layoutVariant: 'full-bleed-divider',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'image-overlay',
        spacingVariant: 'comfortable',
        alignment: 'center',
        ornamentVariant: 'lantern',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'chapter',
        visibilityByViewMode: defaultHidden,
        ornaments: ['lantern'],
        typographySlots: typographyMap.itineraryDivider,
        printBehavior: { pageTemplate: 'chapter', pageBreakBefore: true, pageBreakAfter: true, avoidBreakInside: true },
      }),
      pdf: config('itineraryDivider', {
        layoutVariant: 'full-bleed-divider',
        shellVariant: 'shell-pdf-page',
        backgroundVariant: 'image-overlay',
        spacingVariant: 'page',
        alignment: 'start',
        surfaceStyle: 'full-bleed',
        sectionIntroStyle: 'chapter',
        visibilityByViewMode: defaultHidden,
        ornaments: [],
        typographySlots: typographyMap.itineraryDivider,
        printBehavior: { pageTemplate: 'chapter', pageBreakBefore: true, pageBreakAfter: true, avoidBreakInside: true },
      }),
    },
    itinerary: {
      desktop: config('itinerary', {
        layoutVariant: 'day-story-grid',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'canvas',
        spacingVariant: 'airy',
        alignment: 'start',
        ornamentVariant: 'frame',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        interactionPreset: 'carousel',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.itinerary,
        printBehavior: { pageTemplate: 'editorial', allowCondensedVariant: true, avoidBreakInside: true },
      }),
      mobile: config('itinerary', {
        layoutVariant: 'day-story-grid',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'canvas',
        spacingVariant: 'comfortable',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        mobileOrderStrategy: 'itinerary-stacked',
        interactionPreset: 'carousel',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.itinerary,
        printBehavior: { pageTemplate: 'editorial', allowCondensedVariant: true, avoidBreakInside: true },
      }),
      pdf: config('itinerary', {
        layoutVariant: 'day-story-grid',
        shellVariant: 'shell-pdf-page',
        backgroundVariant: 'canvas',
        spacingVariant: 'page',
        alignment: 'start',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'editorial',
        interactionPreset: 'none',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.itinerary,
        printBehavior: { pageTemplate: 'editorial', allowCondensedVariant: true, avoidBreakInside: true },
      }),
    },
    hotels: {
      desktop: config('hotels', {
        layoutVariant: 'hotel-editorial-odd-even',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'honeyCream',
        spacingVariant: 'airy',
        alignment: 'start',
        ornamentVariant: 'temple',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: ['temple'],
        typographySlots: typographyMap.hotels,
        printBehavior: { pageTemplate: 'editorial', avoidBreakInside: true, pageGroupWithNext: true },
      }),
      mobile: config('hotels', {
        layoutVariant: 'hotel-editorial-odd-even',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'honeyCream',
        spacingVariant: 'comfortable',
        alignment: 'start',
        ornamentVariant: 'temple',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        mobileOrderStrategy: 'hotel-mobile-story',
        visibilityByViewMode: defaultVisible,
        ornaments: ['temple'],
        typographySlots: typographyMap.hotels,
        printBehavior: { pageTemplate: 'editorial', avoidBreakInside: true, pageGroupWithNext: true },
      }),
      pdf: config('hotels', {
        layoutVariant: 'hotel-editorial-odd-even',
        shellVariant: 'shell-pdf-page-framed',
        backgroundVariant: 'honeyCream',
        spacingVariant: 'page',
        alignment: 'start',
        surfaceStyle: 'framed',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.hotels,
        printBehavior: { pageTemplate: 'editorial', avoidBreakInside: true, pageGroupWithNext: true },
      }),
    },
    staysDivider: {
      desktop: config('staysDivider', {
        layoutVariant: 'stays-editorial-split',
        shellVariant: 'shell-none',
        backgroundVariant: 'paper',
        spacingVariant: 'airy',
        alignment: 'split',
        ornamentVariant: 'lantern',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'chapter',
        visibilityByViewMode: defaultVisible,
        ornaments: ['lantern'],
        typographySlots: typographyMap.staysDivider,
        printBehavior: { pageTemplate: 'chapter', pageBreakBefore: true, avoidBreakInside: true },
      }),
      mobile: config('staysDivider', {
        layoutVariant: 'stays-editorial-split',
        shellVariant: 'shell-none',
        backgroundVariant: 'paper',
        spacingVariant: 'comfortable',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'chapter',
        mobileOrderStrategy: 'stays-stacked',
        visibilityByViewMode: defaultVisible,
        ornaments: ['lantern'],
        typographySlots: typographyMap.staysDivider,
        printBehavior: { pageTemplate: 'chapter', pageBreakBefore: true, avoidBreakInside: true },
      }),
      pdf: config('staysDivider', {
        layoutVariant: 'stays-editorial-split',
        shellVariant: 'shell-pdf-page',
        backgroundVariant: 'paper',
        spacingVariant: 'page',
        alignment: 'split',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'chapter',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.staysDivider,
        printBehavior: { pageTemplate: 'chapter', pageBreakBefore: true, avoidBreakInside: true },
      }),
    },
    pricing: {
      desktop: config('pricing', {
        layoutVariant: 'pricing-investment-ledger',
        shellVariant: 'shell-indochine-frame',
        backgroundVariant: 'investment',
        spacingVariant: 'airy',
        alignment: 'split',
        ornamentVariant: 'cloud',
        surfaceStyle: 'framed',
        sectionIntroStyle: 'ledger',
        visibilityByViewMode: defaultVisible,
        ornaments: ['cloud'],
        typographySlots: typographyMap.pricing,
        printBehavior: { pageTemplate: 'pricing', avoidBreakInside: true },
      }),
      mobile: config('pricing', {
        layoutVariant: 'pricing-investment-ledger',
        shellVariant: 'shell-indochine-frame',
        backgroundVariant: 'investment',
        spacingVariant: 'comfortable',
        alignment: 'start',
        ornamentVariant: 'cloud',
        surfaceStyle: 'framed',
        sectionIntroStyle: 'ledger',
        mobileOrderStrategy: 'pricing-stacked',
        visibilityByViewMode: defaultVisible,
        ornaments: ['cloud'],
        typographySlots: typographyMap.pricing,
        printBehavior: { pageTemplate: 'pricing', avoidBreakInside: true },
      }),
      pdf: config('pricing', {
        layoutVariant: 'pricing-investment-ledger',
        shellVariant: 'shell-pdf-page-framed',
        backgroundVariant: 'investment',
        spacingVariant: 'page',
        alignment: 'split',
        surfaceStyle: 'framed',
        sectionIntroStyle: 'ledger',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.pricing,
        printBehavior: { pageTemplate: 'pricing', avoidBreakInside: true },
      }),
    },
    inclusionsExclusions: {
      desktop: config('inclusionsExclusions', {
        layoutVariant: 'inclusions-panels',
        shellVariant: 'shell-none',
        backgroundVariant: 'paper',
        spacingVariant: 'airy',
        alignment: 'split',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.inclusionsExclusions,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
      mobile: config('inclusionsExclusions', {
        layoutVariant: 'inclusions-panels',
        shellVariant: 'shell-none',
        backgroundVariant: 'paper',
        spacingVariant: 'comfortable',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        mobileOrderStrategy: 'inclusions-stacked',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.inclusionsExclusions,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
      pdf: config('inclusionsExclusions', {
        layoutVariant: 'inclusions-panels',
        shellVariant: 'shell-pdf-page',
        backgroundVariant: 'paper',
        spacingVariant: 'page',
        alignment: 'split',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.inclusionsExclusions,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
    },
    paymentTerms: {
      desktop: config('paymentTerms', {
        layoutVariant: 'term-rows',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'paper',
        spacingVariant: 'airy',
        alignment: 'split',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.paymentTerms,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
      mobile: config('paymentTerms', {
        layoutVariant: 'term-rows',
        shellVariant: 'shell-editorial-strip',
        backgroundVariant: 'paper',
        spacingVariant: 'comfortable',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        mobileOrderStrategy: 'terms-stacked',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.paymentTerms,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
      pdf: config('paymentTerms', {
        layoutVariant: 'term-rows',
        shellVariant: 'shell-pdf-page',
        backgroundVariant: 'paper',
        spacingVariant: 'page',
        alignment: 'split',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.paymentTerms,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
    },
    designer: {
      desktop: config('designer', {
        layoutVariant: 'designer-editorial-profile',
        shellVariant: 'shell-indochine-soft',
        backgroundVariant: 'honeyCream',
        spacingVariant: 'airy',
        alignment: 'split',
        ornamentVariant: 'cyclo',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: ['cyclo'],
        typographySlots: typographyMap.designer,
        printBehavior: { pageTemplate: 'designer', avoidBreakInside: true },
      }),
      mobile: config('designer', {
        layoutVariant: 'designer-editorial-profile',
        shellVariant: 'shell-indochine-soft',
        backgroundVariant: 'honeyCream',
        spacingVariant: 'comfortable',
        alignment: 'start',
        ornamentVariant: 'cyclo',
        surfaceStyle: 'paper',
        sectionIntroStyle: 'editorial',
        mobileOrderStrategy: 'designer-stacked',
        visibilityByViewMode: defaultVisible,
        ornaments: ['cyclo'],
        typographySlots: typographyMap.designer,
        printBehavior: { pageTemplate: 'designer', avoidBreakInside: true },
      }),
      pdf: config('designer', {
        layoutVariant: 'designer-editorial-profile',
        shellVariant: 'shell-pdf-page-framed',
        backgroundVariant: 'honeyCream',
        spacingVariant: 'page',
        alignment: 'split',
        surfaceStyle: 'framed',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.designer,
        printBehavior: { pageTemplate: 'designer', avoidBreakInside: true },
      }),
    },
    footer: {
      desktop: config('footer', {
        layoutVariant: 'footer-minimal',
        shellVariant: 'shell-none',
        backgroundVariant: 'canvas',
        spacingVariant: 'tight',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.footer,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
      mobile: config('footer', {
        layoutVariant: 'footer-minimal',
        shellVariant: 'shell-none',
        backgroundVariant: 'canvas',
        spacingVariant: 'tight',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.footer,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
      pdf: config('footer', {
        layoutVariant: 'footer-minimal',
        shellVariant: 'shell-none',
        backgroundVariant: 'transparent',
        spacingVariant: 'tight',
        alignment: 'start',
        surfaceStyle: 'borderless',
        sectionIntroStyle: 'editorial',
        visibilityByViewMode: defaultVisible,
        ornaments: [],
        typographySlots: typographyMap.footer,
        printBehavior: { pageTemplate: 'details', avoidBreakInside: true },
      }),
    },
  },
};
