"""Server-owned, fail-closed Fast Track assembly orchestration."""
from __future__ import annotations

import copy
from collections.abc import Awaitable, Callable
from typing import Any, Literal

from sqlalchemy.ext.asyncio import AsyncSession

from repositories import QuotationDocumentRepository, QuotationRepository
from repositories.errors import DocumentRevisionConflictError
from services.content_action_application_service import (
    ContentActionApplicationService,
    ContentActionPolicyError,
)
from services.fast_track_progress import ProgressEmitter


class FastTrackReviewBlockedError(ValueError):
    def __init__(self, review: dict[str, Any]) -> None:
        super().__init__("Fast Track assembly is incomplete; resolve the reported blockers before opening Design.")
        self.review = review


class FastTrackNotFoundError(ValueError):
    """The quotation or its canonical document does not exist (maps to 404, not 500)."""


class FastTrackAssemblyService:
    """Coordinates media, bypass actions, and canonical readiness without UI policy."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session
        self.documents = QuotationDocumentRepository(session)
        self.quotations = QuotationRepository(session)

    async def assemble(
        self,
        *,
        quotation_id: str,
        lang: str,
        base_revision: int,
        writing_style: Literal["storytelling", "detailed"],
        profile_id: str | None,
        correlation_id: str,
        idempotency_key: str,
        apply_media_defaults: Callable[[dict[str, Any]], Awaitable[dict[str, Any]]],
        normalize_document: Callable[[dict[str, Any], int], dict[str, Any]],
        review_status: Callable[[], Awaitable[dict[str, Any]]],
        progress: ProgressEmitter | None = None,
    ) -> dict[str, Any]:
        quotation = await self.quotations.get_quotation_by_id(quotation_id)
        current = await self.documents.get_current_document(quotation_id, lang)
        if quotation is None or current is None:
            raise FastTrackNotFoundError("Quotation or canonical document was not found.")

        actions_service = ContentActionApplicationService(self.session)
        plan, actions = await actions_service.list(quotation_id)
        bypass_actions = [action for action in actions if action.automation_policy == "bypass"]
        bypass_ids = [action.id for action in bypass_actions if action.state in {"pending", "accepted"}]

        # 16.3 F-05/D4: a same-key retry after a committed assembly must replay the
        # original result, not die on the revision guard (the commit advanced the
        # revision, so the guard would 409 every honest retry).
        applied_ids = [action.id for action in bypass_actions if action.state == "applied"]
        if plan is not None and applied_ids and not bypass_ids:
            try:
                replay = await actions_service.replay_bypass_if_idempotent(
                    quotation_id=quotation_id, plan_id=plan.id, action_ids=applied_ids,
                    idempotency_key=idempotency_key,
                )
            except ContentActionPolicyError:
                replay = None  # applied by a different key — not our retry; fall through
            if replay is not None:
                if progress is not None:
                    await progress.emit(
                        stage="content_generation",
                        message="Reusing content already generated by a previous attempt...",
                        current=len(applied_ids),
                        total=len(applied_ids),
                    )
                review = await review_status()
                if not review.get("ready"):
                    raise FastTrackReviewBlockedError(review)
                if progress is not None:
                    await progress.complete(current_revision=int(review["currentRevision"]))
                return {"status": "complete", "quotationId": quotation_id, "currentRevision": int(review["currentRevision"]), "review": review}

        if current.revision != base_revision:
            raise DocumentRevisionConflictError(quotation_id=quotation_id, lang=lang, expected_revision=base_revision, current_revision=current.revision, current_document=current.document_json)

        if progress is not None:
            await progress.emit(
                stage="facts_media",
                message="Auto-resolving destination and accommodation photography from library...",
            )
        next_document = copy.deepcopy(current.document_json)
        media = await apply_media_defaults(next_document)
        current_revision = current.revision
        document_overlay = normalize_document(next_document, current_revision) if media.get("hasChanges") else None
        if bypass_ids:
            if progress is not None:
                await progress.emit(
                    stage="content_generation",
                    message="Generating storytelling narratives and daily itinerary...",
                    current=0,
                    total=len(bypass_ids),
                )

            async def _report(done: int, total: int) -> None:
                if progress is not None:
                    await progress.emit(
                        stage="content_generation",
                        message="Generating storytelling narratives and daily itinerary...",
                        current=done,
                        total=total,
                    )

            # Plan acceptance commits before generation (16.3 F-20): deliberate.
            # A failed assembly leaves the plan accepted, which is harmless and
            # re-runnable — accept() emits its outbox event only on the first
            # transition, and the retry path replays or regenerates cleanly.
            await actions_service.accept(quotation_id=quotation_id, note="Accepted by explicit Fast Track assembly.", profile_id=profile_id, correlation_id=correlation_id)
            _drafts, current_revision = await actions_service.generate_and_apply(
                quotation_id=quotation_id, plan_id=plan.id, action_ids=bypass_ids,
                expected_revision=current_revision, writing_style=writing_style, profile_id=profile_id,
                correlation_id=correlation_id, idempotency_key=idempotency_key, document_overlay=document_overlay,
                on_action_complete=_report,
            )
        elif document_overlay is not None:
            saved = await self.documents.save_current_document(
                quotation_id=quotation_id, lang=lang, document_json=document_overlay, expected_revision=current_revision,
            )
            document_overlay.setdefault("meta", {})["revision"] = saved.revision
            await self.documents.append_document_revision(
                quotation_id=quotation_id, lang=lang, revision=saved.revision,
                document_json=document_overlay, change_source="fast_track_media_defaults",
            )
            await self.session.commit()
            current_revision = saved.revision

        if progress is not None:
            await progress.emit(stage="review", message="Checking Design readiness...")
        review = await review_status()
        if not review.get("ready"):
            raise FastTrackReviewBlockedError(review)
        if progress is not None:
            await progress.complete(current_revision=int(review["currentRevision"]))
        return {"status": "complete", "quotationId": quotation_id, "currentRevision": int(review["currentRevision"]), "review": review}
