import type {
  AiRunListResponse,
  AiRunStatus,
  AiRunSummary,
  AnalyzeTripResponse,
  ApplyPricingRequestPayload,
  ApplyPricingResponse,
  CostingApplicationProfile,
  CostingDriftProfile,
  CostingSheetProfile,
  CostingSummary,
  CostingWorkbenchResponse,
  DayDraftResult,
  DraftDaySpec,
  DraftDayOutcome,
  DraftServicesResponse,
  PartyComposition,
  RoomAllocation,
  ServiceDraft,
  ServiceDraftFlag,
  ServiceLineAiFlag,
  ServiceLineAiMeta,
  ServiceLineProfile,
  ServiceLineWriteInput,
  TripArchetype,
  TripMobility,
  TripPace,
  TripProfile,
  TripQualityTier,
} from "../../lib/quotationApi.ts";

export type {
  AiRunListResponse,
  AiRunStatus,
  AiRunSummary,
  AnalyzeTripResponse,
  ApplyPricingRequestPayload,
  ApplyPricingResponse,
  CostingApplicationProfile,
  CostingDriftProfile,
  CostingSheetProfile,
  CostingSummary,
  CostingWorkbenchResponse,
  DayDraftResult,
  DraftDaySpec,
  DraftDayOutcome,
  DraftServicesResponse,
  PartyComposition,
  RoomAllocation,
  ServiceDraft,
  ServiceDraftFlag,
  ServiceLineAiFlag,
  ServiceLineAiMeta,
  ServiceLineProfile,
  ServiceLineWriteInput,
  TripArchetype,
  TripMobility,
  TripPace,
  TripProfile,
  TripQualityTier,
};

/** Exactly one of the two is set — a workbench anchors to a request or a quotation (chốt #1). */
export type CostingWorkbenchAnchor = { requestId: string; quotationId?: undefined } | { requestId?: undefined; quotationId: string };
